### PR TITLE
Updated Profile Ui

### PR DESCRIPTION
**Pull request by DillonRego**
Added an edit button to hide the Profile Picture link and the submit button while toggled. Text also changes on toggle from "Edit" to "Close". This same technique can be used inside the Library menu to add edit functionality that is conditionally hidden.

### CODE REVIEW

**Comment by laestevez** [comment]
Looks good to me.

**Comment by AnthonyTennis** [comment]
LGTM

**Comment by SebastianMarino28** [comment]
Looks good, but it seems it now has a conflict with Profile.js, so I would check that out before committing.

**Comment by DillonRego** [comment]
Luis merged this code independently double check and reopen if necessary

**Pull request closed without merging**
